#ifndef SRC_LIGHT_SCHEDULER_H_
#define SRC_LIGHT_SCHEDULER_H_

typedef enum  {
    NONE=-1, EVERYDAY=10, WEEKDAY, WEEKEND,
    SUNDAY=1, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY
} Day;

#endif //SRC_LIGHT_SCHEDULER_H_